# Generated by Django 5.0.6 on 2026-04-06 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_policy_version",
                    models.CharField(default="2026-04-v1", max_length=32),
                ),
                (
                    "candidate_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "retention_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Candidate PII / transcript should not be kept past this time (policy).",
                        null=True,
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="api.interviewsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=16)),
                ("content", models.TextField()),
                ("seq", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="api.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["seq", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="transcriptline",
            constraint=models.UniqueConstraint(
                fields=("session", "seq"), name="api_transcriptline_session_seq_uniq"
            ),
        ),
    ]
