# Generated by Django 5.0.6 on 2026-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="consecutive_bypass_turns",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Server-side streak of skip/next-only candidate lines (enforced guardrail).",
            ),
        ),
    ]
