# Generated by Django 5.0.6 on 2026-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_interviewsession_candidate_rate_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewsession",
            name="consecutive_silent_turns",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Streak of consecutive no-spoken-reply turns (client silence placeholder).",
            ),
        ),
    ]
