# Generated by Django 5.0.6 on 2026-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_interviewsession_consecutive_silent_turns"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="main_question_index",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Count of distinct main screening questions asked so far (excludes follow-ups).",
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="target_questions",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Soft target for number of main questions; can be adjusted dynamically.",
            ),
        ),
    ]
